### ISSUE TITLE
Proposition du projet

### ISSUE THREAD

**Issue by chrisdsa** [chrisdsa/BMS#1]
Remplir le document dans le Drive
- [x] Objectif
- [x] Moyens
- [x] Méthodologie
- [x] Mettre le document au propre
- [x] Relecture
- [x] Envoyer le texte
- [x] Signature du professeur
- [x] Remise du document au département
- [x] Approbation du Directeur

**Comment by bourassajulien** [comment]
Est-ce qu'on met la liste des logiciels ou c'est pas vraiment pertinent pour la proposition?

**Comment by chrisdsa** [comment]
Je ne la mettrais pas, on en parle déjà un peu dans les autres points.

**Comment by bourassajulien** [comment]
J'ai enlevé la mention du "nous" dans le texte. On m'a dit que c'était à proscrire dans les rapports.

**Comment by chrisdsa** [comment]
J'ai envoyé le texte au prof, j'attend ses commentaires.
