### ISSUE TITLE
Ajouter section des risques et méthode mitigation.

### ISSUE THREAD

**Issue by bourassajulien** [chrisdsa/BMS#13]
On peut rajouter les risques comme dans le chapitre 2.4 du livre A Systems Approach. 
On élimine ceux qui s'appliquent pas au projet et comment on va attaquer les autres.
Je ne sais pas si c'est mieux de le mettre dans le cahier des charges ou de conception par contre.

**Comment by chrisdsa** [comment]
En gros dans 2.4 il y a :  
1. Overcharge -> BPS  
2. Overdischarge -> BPS  
3. High temperature -> BPS  
4. Low temperature -> BPS  
5. Overcurrent -> BPS  
6. Internal cell defect  
7. Mechanical shock, crush  
8. Age  

Les points 6-7-8 on pourrait les inclures dans les objectifs futur

**Comment by chrisdsa** [comment]
Une autre section intéressante, chapitre 17 : **Fault Detection**  
1. Overcharge/Overvoltage
2. Over-Temperature  
3. Overcurrent  
4. Battery imbalance / Excessive Self-Discharge  
5. Internal Short Circuit Detection  
6. Detection of lithium plating  
7. Venting Detection  
8. Excessive Capacity Loss

Il parlait aussi dans le livre comment vérifier les différents périphériques. On testerais le relais, la shunt lors de la pré charge, il a des méthodes pour contre valider que les lectures sont bonne en regardant l'ensemble des autres lecture etc. Je peux ajouter ça dans les objectifs :   
- Diagnostique des périphériques / sensors  
- Contre validation des lectures (améliore la robustesse)  
Personnellement je mettrais ça dans les extras
