### ISSUE TITLE
Étudier la faisabilité d'utiliser nOS

### ISSUE THREAD

**Issue by chrisdsa** [chrisdsa/BMS#2]
Conclusion : nOS va être utilisé

**Comment by bourassajulien** [comment]
Documentation: https://github.com/jimtremblay/nOS

**Comment by chrisdsa** [comment]
Ta tu un update sur l'utilisation de nOS? Pour le cahier des charges on va en parler.

**Comment by oclarocque** [comment]
Oui, on va pouvoir l'utiliser. Je vais aussi utiliser le OS abstraction layer de la NASA.

**Comment by chrisdsa** [comment]
nice!
