### ISSUE TITLE
Revoir méthodologie - Cahier des charges

### ISSUE THREAD

**Issue by bourassajulien** [chrisdsa/BMS#3]
Je crois que le cahier des charges c'est plus ce qu'on explique dans la synthèse. Comme vérifier les besoins et dire c'est quel outil a utiliser.
Il faudrait relire ELE400 pour ca.
Mais je crois pas qu'on va se faire refuser pour ca.

**Comment by chrisdsa** [comment]
Le cahier des charges :
1. Contexte et définition du problème
2. Objectifs
3. Périmètre (limites)
4. Description fonctionnelle
5. Spécification détaillée
6. Ressources
7. Échéancier
8. Workflow, Architecture, Méthode  de travail
Source : https://www.manager-go.com/gestion-de-projet/dossiers-methodes/elaborer-un-cdc

**Comment by chrisdsa** [comment]
On est bon avec cette structure pour le cahier des charges?
