### ISSUE TITLE
Réunion de lancement ( Kick off meeting)

### ISSUE THREAD

**Issue by chrisdsa** [chrisdsa/BMS#8]
**Réunion de lancement**  
Quand : Lundi le 1er Mai  15h (Montréal)
Ou : Telegram  
  
**Objectif** : Discuter du cahier des charges et des différents points de vue du projet  
  
**Points à discuter** :  
* Définir un road map global, incluant tous side projects nécessaires (e.g. simulateur de cellule)  
* Discuter de la répartition des tâches de développement pour que les membres se préparent en conséquence (études des méthodologies, des logiciels, des technologies..)  
* Définir les objectifs et le degré de complexité (pour le cours et la compétition)
* Horaire des membres et disponibilités
* Meeting entre les membres
* Meeting avec le professeur
* Gestion du budget (sur quoi on met les ressources)
* Gestion de projet (gantt? division en semaine)
* Recherche documentation et partage des connaissances
* Schéma bloc du projet
  
Voir issue `Revoir méthodologie - Cahier des charges #3` pour la description du cahier des charges

**Comment by oclarocque** [comment]
*Définir un road map global, incluant tous side projects nécessaires (e.g. simulateur de cellule)
*Discuter de la répartition des tâches de développement pour que les membres se préparent en conséquence (études des méthodologies, des logiciels, des technologies..)

**Comment by bourassajulien** [comment]
* Horaire des membres et disponibilités
* Meeting entre les membres
* Meeting avec le professeur
* Gestion du budget (sur quoi on met les ressources)
* Gestion de projet (gantt? division en semaine)
* Recherche documentation et partage des connaissances
* Schéma bloc du projet
